version: '3'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
